language: node_js

cache:
  directories:
    - ~/.npm
    - node_modules

node_js: stable

# S: Build Lifecycle
install:
  - yarn


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "ray0324"
  - git config user.email "ray0324@foxmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle


branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/ray0324/ray0324.github.io.git