# theme

# 导航
nav:
  home:
    text: 首页
    url: /
  archives:
    text: 归档
    url: /archives/
  tags: 
    text: 标签
    url: /tags/
  about: 
    text: 关于
    url: /about/

# github
github: http://github.com/ray0324
